theHamsta/nvim-dap-virtual-text

lua/nvim-dap-virtual-text/virtual_text.lua

The use of `M` for defining some sort of public API in lua modules seems to be a common pattern. I came across an issue in another neovim plugin where the author forgot to add a `local` keyword to this variable which cased some sort of collision and prevented it from operating properly.
This commit should prevent this from happening.

Fix leaking global variable

---

lua/nvim-dap-virtual-text.lua
plugin/nvim-dap-virtual-text.vim

This should reduce plugin activation time by not requiring all of nvim-treesitter. I'm still thinking about removing https://github.com/theHamsta/nvim-dap-virtual-text/blob/master/plugin/nvim-dap-virtual-text.vim

Defer requireing of nvim-dap-virtual-text

---

README.md
lua/nvim-dap-virtual-text/virtual_text.lua

Having the virtual text additionally use comment syntax further improves distinguishability between actual code and debugger info.
Adds an option `g:dap_virtual_text_commented` to enable this.
Uses `commentstring` for "commenting" the virtual text.

Add optional support for commented virtual text

---

lua/nvim-dap-virtual-text.lua

Fixes a small typo for new usage instructions introduced in 4b6508200201538dc5ccc48b7c36378ac7f37a5b

Fix typo in new deprecation message

---

lua/nvim-dap-virtual-text/virtual_text.lua

Previously, all the names of all scopes where mixed together.
Now, we make sure that we prefer variables of the "locals" scope over
globals or registers.

Prefer scopes with "locals" presentationHint

---

lua/nvim-dap-virtual-text.lua
lua/nvim-dap-virtual-text/virtual_text.lua

Always update last_frames and remember them even if the are missing in one instance of a stopped threads. They might appear later again when you return to a frame that is higher in the call hierarchy.

Remember last frames longer

---

lua/nvim-dap-virtual-text.lua

The options were not passed to `set_error` when the debugger halted on an exception, resulting in a crash because `options.error_prefix` is accessed (ever since being configured in `.setup()`).

Fix missing options of `set_error` for exceptions

---

lua/nvim-dap-virtual-text/virtual_text.lua

Fixes #27
@panders23 can you test this? If there are other flaws with the php locals, please try to fix them at nvim-treesitter. Sorry for missunderstanding your issue. I thought nvim-treesitter had the dollar signs while in fact the debug adapter had them!

fix compatibility with vscode-php-adapter: trim leading $ from variables

---

lua/nvim-dap-virtual-text/virtual_text.lua

Hey :smile: Found this issue when diagnosing https://github.com/rcarriga/nvim-dap-ui/issues/66. Because `list_extend` mutates the first argument, if multiple variable calls are made then the frame scopes are duplicated for each call leading to it getting exponentially bigger, quickly causing a memory issue. I just switched the order of the params to avoid this.

fix: prevent frame mutation

---

lua/nvim-dap-virtual-text/virtual_text.lua

This fixes virtual text having `Normal` bg with `cursorline` and the stopped line - the default highlighting for the DapStopped sign's `line_hl` is `debugPc`

add hl_mode = combine

---

lua/nvim-dap-virtual-text.lua

The descriptions are copied from README.md
Result:

docs: add type annotations for options

---

.github/workflows/style-check.yml
lua/nvim-dap-virtual-text/virtual_text.lua

fix: sanitize usage of gsub for replacement string that contain "%"

---

README.md
lua/nvim-dap-virtual-text.lua
lua/nvim-dap-virtual-text/virtual_text.lua

Addresses #47, #48
@przepompownia does this solve your problems? If you could install a listener for `dap.listeners.after.variables` to decide which variables you want to evaluate. Store the results of  the evaluations somewhere and `refresh` of this plugin once you got the response for all your evaluate requests.

feat: add display_callback option

---

README.md

The indent breaks the GitHub copy functionality

docs: fix indent for install snippet

---

lua/nvim-dap-virtual-text/virtual_text.lua

Some debug adapters occasionally create a stack frame in a brand new buffer, e.g. if jumping into memory that requires disassembly. For some reason, there are rare cases where nvim-dap fires listener events on the new frame before Neovim has had the chance to determine the filetype. Since the filetype is empty, tree-sitter throws an error on `get_parser()`.
This fix manually calls `vim.filetype.match()` on the buffer if the filetype is empty. If still empty, the function exits early.
So, this fixes the rare edge case I was experiencing, as well as any potential case where Neovim cannot determine the filetype of the file being stepped into.

Prevent tree-sitter error on buffers that don't yet have a filetype

---

lua/nvim-dap-virtual-text/virtual_text.lua

Fix for issue #75 
Just cleared the `node` key in `content` before passing it to the `nvim_buf_set_extmark()`, similar to how it's done in case of virt_text option (ie, when virt_lines=false).

fix for cannot convert lua table error when virt_lines=true

---

lua/nvim-dap-virtual-text.lua
lua/nvim-dap-virtual-text/virtual_text.lua

This pretty much reverts commit 57f1dbd, as it causes issues when toggling / disabling virtual text (see #74)
I haven't noticed any flickering, but I haven't tested extensively either

fix: revert workaround to reduce flickering

---

lua/nvim-dap-virtual-text/virtual_text.lua

Fixes #71 for any filetype that does not have a treesitter parser installed (encountered on powershell files)

fix(treesitter): fail gracefully if no lang is found for a filetype

---

README.md
lua/nvim-dap-virtual-text.lua

Hello! It's me again!
I've noticed that when a variable contains newline characters, the virtual text displayed isn't very nice:
Notice the extraneous `^@` everywhere. Recently, someone noticed a similar issue with code lenses [upstream](https://github.com/neovim/neovim/issues/28794), and I thought it'd be a nice idea to apply the same [fix](https://github.com/neovim/neovim/pull/28807/commits/ea0a9163cb37e8444465b81abbed82c54134c12e) in the default configuration here. It looks like this:
Which isn't perfect either, but IMO it's a clear improvement.

fix: handle line breaks

---

lua/nvim-dap-virtual-text/virtual_text.lua

While debugging Java with nvim-jdtls, step debugging into source associated with a dependency would result in an error locating the treesitter parser.
The code at the top of `set_virtual_text` tries to locate the buffer associated with the source of the dap stack frame by transforming `source.path` to a URI with `uri_from_fname` before calling `uri_to_bufnr` to locate the buffer. This works well for the common case of file names, but fails for cases where `source.path` is already a URI.
When an existing URI is provided to `uri_from_fname`, it undergoes another set of encoding and get prefixed with at `file://` scheme. This new URI is not associated with any existing buffer, so `uri_to_bufnr` creates a new buffer. Since the new buffer has no associated filetype, the code attempts to …

Avoid creating buffer when locating bufnr

---

lua/nvim-dap-virtual-text/virtual_text.lua

`Query:iter_matches` returns a `TSNode[]` iterator, but it was previously being treated a single `TSNode`. See [`:h Query:iter_matches()`](https://neovim.io/doc/user/treesitter.html#Query%3Aiter_matches()).
Note: I haven't tested this change in earlier nvim versions to see if it's backwards-compatible.
fixes #85
Related: https://github.com/neovim/neovim/pull/30193

fix: iterate over all nodes (#85)

---

lua/nvim-dap-virtual-text/virtual_text.lua

After #87, this plugin became incompatible with nvim versions <= 0.9 by using the newly table parameter of iter_matches. This PR tries to avoid the parameter and tries to account that iter_matches might return either nodes or tables of nodes by coercing non-table values to singleton tables.
Fixes https://github.com/theHamsta/nvim-dap-virtual-text/issues/88

fix: Restore compatibilty with nvim<=0.9

---

lua/nvim-dap-virtual-text.lua

This PR fixes a bug where virtual text is not cleared when the debugger is continued through a continue request. The issue arises because the continued event is not emitted for continue requests, as per [DAP documentation](https://microsoft.github.io/debug-adapter-protocol/specification#Events_Continued). To resolve this, a listener for the continue request has been added to ensure the virtual text is cleared as expected.

fix: clear virtual text on continue request
